# -*- coding: utf-8 -*-
"""CV_Practical9_28.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lnzpFL75Lnb9HVHtlTLBr4xZYPDFg1n-
"""

## Implement Facial Expression Recognition.

!pip install DeepFace opencv-python

import cv2
from deepface import DeepFace

# Load image
image_path = "test.webp"
img = cv2.imread(image_path)

# Load face detector
face_cascade = cv2.CascadeClassifier(
    cv2.data.haarcascades + "haarcascade_frontalface_default.xml"
)

# Convert image to grayscale
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Detect faces
faces = face_cascade.detectMultiScale(gray, 1.3, 5)

for (x, y, w, h) in faces:

    # Crop face
    face = img[y:y+h, x:x+w]

    try:
        # Predict emotion
        result = DeepFace.analyze(face, actions=['emotion'], enforce_detection=False)
        emotion = result[0]['dominant_emotion']

        # Draw rectangle
        cv2.rectangle(img, (x,y), (x+w,y+h), (0,255,0), 2)

        # Put emotion label
        cv2.putText(img, emotion, (x, y-10),
                    cv2.FONT_HERSHEY_SIMPLEX,
                    0.9, (0,255,0), 2)

    except:
        pass

# Show output
from google.colab.patches import cv2_imshow

# Show output in Colab
cv2_imshow(img)