# -*- coding: utf-8 -*-
"""OT_Pr4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fv-9nNIiepWNQUlKyj_8MTVpdKIoSV9k
"""

import sympy as sp

# define variables

x,y,lam = sp.symbols("x y lam")

# Objective function

f = x*y

# Constraint function

g = x+y-10

# Langragian function

L = f + lam*g

# partial derivative

eq1 = sp.diff(L,x)
eq2 = sp.diff(L,y)
eq3 = sp.diff(L,lam)

# solve equation

sol = sp.solve([eq1,eq2,eq3],(x,y,lam))

print("Optimal Solution: ", sol)

# objective function value

x_val = sol[x]
y_val = sol[y]

f_val = x_val*y_val

print("Objective function value: ", f_val)