# -*- coding: utf-8 -*-
"""OT_Pr3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d1JNqHCfFgCNc3NMP6jdM6FD0IBHNDSX
"""

import sympy as sp

x = sp.Symbol("x")

# constraint is - x+y = 10
y = 10-x

# objective function
f = x**2 + y**2

print("Objective function after substitution")
print(sp.expand(f))

# First Derivative
f_prime = sp.diff(f,x)

print("First Derivative")
print(f_prime)

# crititcal point

critical_point = sp.solve(f_prime,x)

print("Critical Point")
print(critical_point)

# double derivative

f_double = sp.diff(f_prime,x)

print("Double Derivative")
print(f_double)

# optimal point calculation

for point in critical_point:
  y_value = y.subs(x,point)
  print("\nOptimal Point")
  print("x = ",point)
  print("y = ",y_value)

# decision

if f_double.subs(x,point) > 0:
  print("Minimum Point")
  print("Minimum Value = ",f.subs(x,point))
elif f_double.subs(x,point) < 0:
  print("Maximum Point")
  print("Maximum Value = ",f.subs(x,point))
else:
  print("No Decision")

print("Objective Function Value = ", f.subs(x, point))