# -*- coding: utf-8 -*-
"""OT_Pr2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q-glmNjjaILHvWLoBE7NssAC2BufVC2F
"""

import sympy as sp

x,y = sp.symbols('x y')

#f = x**2 + y**2 - 4*x -6*y + 13
f = x**2 + y**2 +8*x- 12*y + 2

print(f"Function: {f}")

fx = sp.diff(f,x)
fy = sp.diff(f,y)

print(f"Partial Derivative w.r.t x: {fx}")
print(f"Partial Derivative w.r.t y: {fy}")

critical_points = sp.solve((fx,fy),(x,y))
print(f"Critical Points: {critical_points}")

fxx = sp.diff(fx,x)
fyy = sp.diff(fy,y)
fxy = sp.diff(fx,y)

D = fxx*fyy - fxy**2

print(f"fxx: {fxx}")
print(f"fyy: {fyy}")
print(f"fxy: {fxy}")
print(f"D: {D}")

if D > 0 and fxx > 0:
  print("Local Minima")
elif D > 0 and fyy < 0:
  print("Local Maxima")
elif D < 0:
  print("Saddle Point")
else:
  print("Inconclusive")