# -*- coding: utf-8 -*-
"""RL_2_28.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OP0McM_HNUoy6nlfyiZ6tpNTdqAhLxiP
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Loading the Dataset

data = pd.read_csv(r"Iris.csv")
data.head()

# Data Mining

is_null = data.isnull().sum().sum() # checking for null values
if (is_null == 0):
  print("Data has no null values")

print("Shape: " , data.shape) # dimension the datasets.

# checking the uniques class labels
print("Unique class labels:",data["Species"].value_counts())
print("\n")

# Descriptive analysis of data
print("Descriptive Analysis of Data:",data.describe())  # no outliers detected.
print("\n")

# Overview of the datasets
data.info()

# Data Visualization

sns.pairplot(data, hue = "Species")
plt.show()

