# -*- coding: utf-8 -*-
"""RL_7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A4kMEd6FQ29DPaA20jzcglRzUH4rxq0T
"""

import gymnasium as gym
import numpy as np
import random

# Initialize environment
env = gym.make("Taxi-v3", render_mode="ansi")

# 1. Initialize Q-Table with zeros
q_table = np.zeros([env.observation_space.n, env.action_space.n])

# 2. Hyperparameters
alpha = 0.1    # Learning rate
gamma = 0.6    # Discount factor (future reward importance)
epsilon = 0.1  # Exploration rate (chance to try random moves)

# 3. Training Loop
for i in range(1, 10001):
    state, info = env.reset()
    terminated = False
    truncated = False

    while not (terminated or truncated):
        # Exploration vs. Exploitation
        if random.uniform(0, 1) < epsilon:
            action = env.action_space.sample() # Explore random move
        else:
            action = np.argmax(q_table[state]) # Exploit best known move

        next_state, reward, terminated, truncated, info = env.step(action)

        # Update Q-value using the Bellman Equation
        old_value = q_table[state, action]
        next_max = np.max(q_table[next_state])

        new_value = (1 - alpha) * old_value + alpha * (reward + gamma * next_max)
        q_table[state, action] = new_value

        state = next_state

    if i % 1000 == 0:
        print(f"Episode: {i} completed")

print("Training finished.\n")

state, info = env.reset()
terminated = False
truncated = False

while not (terminated or truncated):
    action = np.argmax(q_table[state])
    state, reward, terminated, truncated, info = env.step(action)
    print(env.render()) # Visualizes the taxi moving on the grid

