# -*- coding: utf-8 -*-
"""SDA_7_28.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NelI47MW5DfEIWKANpfUYl28M1swbxJt

To design and train a basic Artificial Neural Network (ANN) for a
classification problem using Python and evaluate its performance.
"""

## Import Libraries

import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

## Load the datasets

df = pd.read_csv("data-.csv")
df.head()

## Data Pre-processing

df.drop(['id', 'Unnamed: 32'], axis=1, inplace=True)
df['diagnosis'] = df['diagnosis'].map({'M': 1, 'B': 0})

df.shape

df.isna().sum()  ## cleaned the datasets

## Split the dataset

X = df.drop('diagnosis', axis=1)
y = df['diagnosis']

## Train0test split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

## Standardize the data

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

## Designin the ANN

model = Sequential()
model.add(Dense(units=5, activation='relu', input_dim=X_train.shape[1])) # Input layer + 1st hidden layer
model.add(Dense(units=1, activation='sigmoid')) # Output layer for binary classification

## Compile and train the model

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
# Train the model with validation data
history = model.fit(
    X_train,
    y_train,
    epochs=10,
    batch_size=2,
    verbose=1,
    validation_data=(X_test, y_test)  # This enables val_loss and val_accuracy
)

## Model Evaluation

loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print(f"Test Accuracy: {accuracy*100:.2f}%")

##Prediction

y_pred_probs = model.predict(X_test)
y_pred = (y_pred_probs > 0.5).astype(int).flatten() # Convert probabilities to binary classes

## Confusion metrics

print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

