# -*- coding: utf-8 -*-
"""SDA_3_28

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xh4g-UTmin7xpnteCyZ0aoW5euZcVZlY
"""

# Import libraries
import pandas as pd
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Load the datastes
data = load_breast_cancer()  # sklearn datasets - clean and handled

X = data.data
y = data.target

# train test split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

# Decision Tree Classifier

dt_model = DecisionTreeClassifier(random_state=42)

dt_model.fit(X_train, y_train)

dt_train_pred = dt_model.predict(X_train)
dt_test_pred = dt_model.predict(X_test)

dt_train_acc = accuracy_score(y_train, dt_train_pred)
dt_test_acc = accuracy_score(y_test, dt_test_pred)

# Random Forest Classifier

rf_model = RandomForestClassifier(n_estimators=100, random_state=42)

rf_model.fit(X_train, y_train)

rf_train_pred = rf_model.predict(X_train)
rf_test_pred = rf_model.predict(X_test)

rf_train_acc = accuracy_score(y_train, rf_train_pred)
rf_test_acc = accuracy_score(y_test, rf_test_pred)

# Compare Results

print("Decision Tree Training Accuracy:", dt_train_acc)
print("Decision Tree Testing Accuracy :", dt_test_acc)

print("\nRandom Forest Training Accuracy:", rf_train_acc)
print("Random Forest Testing Accuracy :", rf_test_acc)

print("\nOverfitting Analysis:")

if dt_train_acc > dt_test_acc:
    print("Decision Tree shows signs of overfitting.")

if rf_train_acc > rf_test_acc:
    print("Random Forest reduces overfitting compared to Decision Tree.")

