# -*- coding: utf-8 -*-
"""SDA_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1abBvgcGxLInvtGircYAbnkfRtphlNcss
"""

# Import libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error, root_mean_squared_error, r2_score

# Loading the datasets

data = pd.read_csv("student_scores.csv")
data.head()

# Data Pre-processing

print("Shape: ",data.shape)
print("Null values :",data.isnull().sum().sum())
print("Na values :",data.isna().sum().sum())

# EDA

data.info()

data.describe()

# Splliting the data

X = data.iloc[:, 0:1]
y = data["Scores"]

# Plotting the data

plt.title("Hours v/s Score")
plt.scatter(X,y,color = "blue", label = "data_points")
plt.xlabel("Hours")
plt.ylabel("Scores")

# Train-test split

x_train,x_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 42)
x_train.shape
y_train.shape

# Training the model

Lr = LinearRegression()
model = Lr.fit(x_train,y_train)
print("Coeff: ",model.coef_)
print("Intercept: ",model.intercept_)
model.score(X,y)

# Model Evaluation

y_pred = model.predict(x_test)
print("MAE :",mean_absolute_error(y_test,y_pred))
print("MSE :",mean_squared_error(y_test,y_pred))
print("RMSE :",root_mean_squared_error(y_test,y_pred))
print("R2 :",r2_score(y_test,y_pred))

# Plotting the prediction

plt.scatter(x_test, y_test, color='blue', label='Actual Data')        # Plot actual data points
plt.plot(x_test, y_pred, color='red', linewidth=2, label='Prediction Line') # Plot the prediction line

plt.title('Actual vs. Predicted Values')
plt.xlabel('Hours')
plt.ylabel('Scores')
plt.legend()
plt.grid(True)
plt.show()

