# -*- coding: utf-8 -*-
"""SDA_1_28.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QT81X585ePPAsX0Qd5xroWRz2o5MrtvY
"""

## import libraries

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler

## Load the datasets

data = sns.load_dataset('titanic')
data.head()

data.shape

## Data Cleaning

data = data.drop_duplicates()

## Handle missing values

print(data.isna().sum())  # overview

data['age'].fillna(data['age'].mean(), inplace = True)  # fill the numeric values with mean

data['embarked'].fillna(data['embarked'].mode()[0], inplace = True) # fill thecategorical values with mode.
data['embark_town'].fillna(data['embark_town'].mode()[0], inplace = True)

data = data.drop(columns=['deck']) # drop the column with high missing values.

## Checking the data

print(data.isna().sum().sum())

print(data.shape)

## data cleaned.

## Normalization

scaler = MinMaxScaler()

numerical_cols = ['age', 'fare']
data[numerical_cols] = scaler.fit_transform(data[numerical_cols])

print("\nData after preprocessing:")
print(data.head())

## Data Visualization

# Histogram
data['age'].hist()
plt.title("Age Distribution")
plt.xlabel("Age")
plt.ylabel("Frequency")
plt.show()

# Count Plot
sns.countplot(x='survived', data=data)
plt.title("Survival Count")
plt.show()

# Scatter Plot
plt.scatter(data['age'], data['fare'])
plt.xlabel("Age")
plt.ylabel("Fare")
plt.title("Age vs Fare")
plt.show()

