# -*- coding: utf-8 -*-
"""SDA_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gdGkHPfebTkzhIJaG8myDd79YJfHH12H

## Linearly Separable Data using SVM
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.svm import LinearSVC
from sklearn.metrics import confusion_matrix

# Loading the datsets

data = pd.read_csv("IRIS.csv")
data.head()

# Data Pre-Processing

is_na = data.isna().sum().sum()
if not is_na:
  print("data has no na values")

# EDA

print("Info:\n", data.info)
print("\n\nDescriptive Summary:\n", data.describe)
print("\n\n Unique Classes:\n", data['species'].value_counts())

# Spitting the features and label

X = data.iloc[:,:-1]
y = data['species']

print("Dimension of X:",X.shape)
print("Dimesnion of y:",y.shape)

X

# Train-test split

x_train,x_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state= 42)

# Training the model

model = LinearSVC()
linear_clf = model.fit(x_train,y_train)

# Prediction

y_pred = linear_clf.predict(x_test)

# Model Evaluation

from sklearn.metrics import (
    confusion_matrix,
    ConfusionMatrixDisplay, # display the confusion matrix
    accuracy_score,
    precision_recall_curve, # Fixed: precision (one 's')
    roc_curve,
    precision_score,        # Fixed: precision (one 's')
    recall_score,           # Fixed: recall (one 'c', two 'l's)
    f1_score
)

# Model Evaluation

print(f"Accuracy Score: {accuracy_score(y_test, y_pred):.4f}")

# Plot Confusion Matrix
cm = confusion_matrix(y_test, y_pred)

disp = ConfusionMatrixDisplay.from_predictions(y_test, y_pred, cmap=plt.cm.Blues)
plt.title("Confusion Matrix")
plt.show()

"""## Non- Linear Data using SVM"""

import pandas as pd
import os
from skimage.transform import resize
from skimage.io import imread
import numpy as np
import matplotlib.pyplot as plt
from sklearn import svm
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

# Loading the datasets

Categories = ['cat', 'dog']

def load_data(folder_path):
    flat_data_arr = []
    target_arr = []
    for i in Categories:
        path = os.path.join(folder_path, i)
        for img in os.listdir(path):
            try:
                img_array = imread(os.path.join(path, img))
                img_resized = resize(img_array, (150, 150, 3))
                flat_data_arr.append(img_resized.flatten())
                target_arr.append(Categories.index(i))
            except:
                continue
    return np.array(flat_data_arr), np.array(target_arr)

# 1. Load Training Data
x_train, y_train = load_data('IMAGES/train/')
print(f"Train data loaded: {x_train.shape}")

# 2. Load Test Data
x_test, y_test = load_data('IMAGES/test/')
print(f"Test data loaded: {x_test.shape}")

model = svm.SVC(kernel='rbf', probability=True)
model.fit(x_train, y_train)
print("Model training complete.")

y_pred = model.predict(x_test)
y_pred

from sklearn.metrics import (
    confusion_matrix,
    ConfusionMatrixDisplay, # display the confusion matrix
    accuracy_score,
    precision_recall_curve, # Fixed: precision (one 's')
    roc_curve,
    precision_score,        # Fixed: precision (one 's')
    recall_score,           # Fixed: recall (one 'c', two 'l's)
    f1_score
)

print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=Categories))

cm = confusion_matrix(y_test, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=Categories)

disp.plot(cmap=plt.cm.Blues)
plt.title("Confusion Matrix: Cat vs Dog")
plt.show()

from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC

# 1. Define the parameter grid
# C: Controls the trade-off between smooth boundary and classifying training points correctly.
# Gamma: Defines how far the influence of a single training example reaches.
param_grid = {
    'C': [0.1, 1, 10, 100],
    'gamma': [0.0001, 0.001, 0.01, 0.1],
    'kernel': ['rbf', 'poly']
}

# 2. Initialize the Grid Search
# cv=5 means 5-fold cross-validation
grid = GridSearchCV(SVC(probability=True), param_grid, cv=5, verbose=2)

# 3. Fit the model (this may take a few minutes depending on dataset size)
grid.fit(x_train, y_train)

# 4. Print the best parameters found
print(f"Best Parameters: {grid.best_params_}")

# 5. Evaluate the optimized model
grid_predictions = grid.predict(x_test)
print(classification_report(y_test, grid_predictions, target_names=Categories))

import matplotlib.pyplot as plt

# 1. Select the number of images to display
n_images = 10
fig, axes = plt.subplots(2, 5, figsize=(15, 7))
axes = axes.ravel()

for i in range(n_images):
    # Reshape the flattened test data back to (150, 150, 3)
    img = x_test[i].reshape(150, 150, 3)

    axes[i].imshow(img)

    # Get the names for labels
    true_label = Categories[y_test[i]]
    pred_label = Categories[y_pred[i]]

    # Color code: Green for correct, Red for wrong
    color = 'green' if true_label == pred_label else 'red'

    axes[i].set_title(f"True: {true_label}\nPred: {pred_label}", color=color)
    axes[i].axis('off')

plt.tight_layout()
plt.show()

